#pragma once

#include <stdint.h>

namespace WaveSabreCore::M7
{
// clang-format off
// you need to sync up all these enums below to correspond with ordering et al.
enum class GigaSynthParamIndices : uint16_t
{
  MasterVolume,
  Pan,
  VoicingMode,
  Unisono,
  UnisonoDetune,
  UnisonoStereoSpread,
  FMBrightness,

  PortamentoTime,
  PitchBendRange,

  MaxVoices,

  Macro1,
  Macro2,
  Macro3,
  Macro4,
  Macro5,
  Macro6,
  Macro7,

  FMAmt2to1,
  FMAmt3to1,
  FMAmt4to1,
  FMAmt1to2,
  FMAmt3to2,
  FMAmt4to2,
  FMAmt1to3,
  FMAmt2to3,
  FMAmt4to3,
  FMAmt1to4,
  FMAmt2to4,
  FMAmt3to4,

  Osc1Enabled,  // KEEP IN SYNC WITH OscParamIndexOffsets
  Osc1Volume,
  Osc1Pan,
  Osc1CompensationGain,
  Osc1KeyrangeMin,
  Osc1KeyrangeMax,

  Osc1Waveform,
  Osc1WaveshapeA,
  Osc1WaveshapeB,
  Osc1PhaseRestart,
  Osc1PhaseOffset,
  Osc1SyncEnable,
  Osc1SyncFrequency,
  Osc1SyncFrequencyKT,
  Osc1FrequencyParam,
  Osc1FrequencyParamKT,
  Osc1PitchSemis,
  Osc1PitchFine,
  Osc1FreqMul,
  Osc1FMFeedback,

  Osc1AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Osc1AmpEnvAttackTime,
  Osc1AmpEnvAttackCurve,
  Osc1AmpEnvHoldTime,
  Osc1AmpEnvDecayTime,
  Osc1AmpEnvDecayCurve,
  Osc1AmpEnvSustainLevel,
  Osc1AmpEnvReleaseTime,
  Osc1AmpEnvReleaseCurve,
  Osc1AmpEnvLegatoRestart,
  Osc1AmpEnvMode,

  Osc2Enabled,  // KEEP IN SYNC WITH OscParamIndexOffsets
  Osc2Volume,
  Osc2Pan,
  Osc2CompensationGain,
  Osc2KeyrangeMin,
  Osc2KeyrangeMax,
  Osc2Waveform,
  Osc2WaveshapeA,
  Osc2WaveshapeB,
  Osc2PhaseRestart,
  Osc2PhaseOffset,
  Osc2SyncEnable,
  Osc2SyncFrequency,
  Osc2SyncFrequencyKT,
  Osc2FrequencyParam,
  Osc2FrequencyParamKT,
  Osc2PitchSemis,
  Osc2PitchFine,
  Osc2FreqMul,
  Osc2FMFeedback,

  Osc2AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Osc2AmpEnvAttackTime,
  Osc2AmpEnvAttackCurve,
  Osc2AmpEnvHoldTime,
  Osc2AmpEnvDecayTime,
  Osc2AmpEnvDecayCurve,
  Osc2AmpEnvSustainLevel,
  Osc2AmpEnvReleaseTime,
  Osc2AmpEnvReleaseCurve,
  Osc2AmpEnvLegatoRestart,
  Osc2AmpEnvMode,

  Osc3Enabled,  // KEEP IN SYNC WITH OscParamIndexOffsets
  Osc3Volume,
  Osc3Pan,
  Osc3CompensationGain,
  Osc3KeyrangeMin,
  Osc3KeyrangeMax,
  Osc3Waveform,
  Osc3WaveshapeA,
  Osc3WaveshapeB,
  Osc3PhaseRestart,
  Osc3PhaseOffset,
  Osc3SyncEnable,
  Osc3SyncFrequency,
  Osc3SyncFrequencyKT,
  Osc3FrequencyParam,
  Osc3FrequencyParamKT,
  Osc3PitchSemis,
  Osc3PitchFine,
  Osc3FreqMul,
  Osc3FMFeedback,

  Osc3AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Osc3AmpEnvAttackTime,
  Osc3AmpEnvAttackCurve,
  Osc3AmpEnvHoldTime,
  Osc3AmpEnvDecayTime,
  Osc3AmpEnvDecayCurve,
  Osc3AmpEnvSustainLevel,
  Osc3AmpEnvReleaseTime,
  Osc3AmpEnvReleaseCurve,
  Osc3AmpEnvLegatoRestart,
  Osc3AmpEnvMode,

  Osc4Enabled,  // KEEP IN SYNC WITH OscParamIndexOffsets
  Osc4Volume,
  Osc4Pan,
  Osc4CompensationGain,
  Osc4KeyrangeMin,
  Osc4KeyrangeMax,
  Osc4Waveform,
  Osc4WaveshapeA,
  Osc4WaveshapeB,
  Osc4PhaseRestart,
  Osc4PhaseOffset,
  Osc4SyncEnable,
  Osc4SyncFrequency,
  Osc4SyncFrequencyKT,
  Osc4FrequencyParam,
  Osc4FrequencyParamKT,
  Osc4PitchSemis,
  Osc4PitchFine,
  Osc4FreqMul,
  Osc4FMFeedback,

  Osc4AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Osc4AmpEnvAttackTime,
  Osc4AmpEnvAttackCurve,
  Osc4AmpEnvHoldTime,
  Osc4AmpEnvDecayTime,
  Osc4AmpEnvDecayCurve,
  Osc4AmpEnvSustainLevel,
  Osc4AmpEnvReleaseTime,
  Osc4AmpEnvReleaseCurve,
  Osc4AmpEnvLegatoRestart,
  Osc4AmpEnvMode,

  Env1DelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Env1AttackTime,
  Env1AttackCurve,
  Env1HoldTime,
  Env1DecayTime,
  Env1DecayCurve,
  Env1SustainLevel,
  Env1ReleaseTime,
  Env1ReleaseCurve,
  Env1LegatoRestart,
  Env1AmpEnvMode,

  Env2DelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Env2AttackTime,
  Env2AttackCurve,
  Env2HoldTime,
  Env2DecayTime,
  Env2DecayCurve,
  Env2SustainLevel,
  Env2ReleaseTime,
  Env2ReleaseCurve,
  Env2LegatoRestart,
  Env2AmpEnvMode,

  Env3DelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Env3AttackTime,
  Env3AttackCurve,
  Env3HoldTime,
  Env3DecayTime,
  Env3DecayCurve,
  Env3SustainLevel,
  Env3ReleaseTime,
  Env3ReleaseCurve,
  Env3LegatoRestart,
  Env3AmpEnvMode,

  Env4DelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Env4AttackTime,
  Env4AttackCurve,
  Env4HoldTime,
  Env4DecayTime,
  Env4DecayCurve,
  Env4SustainLevel,
  Env4ReleaseTime,
  Env4ReleaseCurve,
  Env4LegatoRestart,
  Env4AmpEnvMode,

  LFO1Waveform,  // KEEP IN SYNC WITH LFOParamIndexOffsets
  LFO1WaveshapeA,
  LFO1WaveshapeB,
  LFO1Restart,  // if restart, then LFO is per voice. if no restart, then it's per synth.
  LFO1PhaseOffset,
  LFO1FrequencyParam,
  LFO1TimeBasis, // enum TimeBasis
    LFO1BeatNumerator,
    LFO1BeatDenominator,
    LFO1EighthsFine,    // -1 to 1 8th
    LFO1MS,      // -200,200 ms
  LFO1Sharpness,

  LFO2Waveform,  // KEEP IN SYNC WITH LFOParamIndexOffsets
  LFO2WaveshapeA,
  LFO2WaveshapeB,
  LFO2Restart,  // if restart, then LFO is per voice. if no restart, then it's per synth.
  LFO2PhaseOffset,
  LFO2FrequencyParam,
  LFO2TimeBasis, // enum TimeBasis
    LFO2BeatNumerator,
    LFO2BeatDenominator,
    LFO2EighthsFine,    // -1 to 1 8th
    LFO2MS,      // -200,200 ms
  LFO2Sharpness,

  LFO3Waveform,  // KEEP IN SYNC WITH LFOParamIndexOffsets
  LFO3WaveshapeA,
  LFO3WaveshapeB,
  LFO3Restart,  // if restart, then LFO is per voice. if no restart, then it's per synth.
  LFO3PhaseOffset,
  LFO3FrequencyParam,
  LFO3TimeBasis, // enum TimeBasis
    LFO3BeatNumerator,
    LFO3BeatDenominator,
    LFO3EighthsFine,    // -1 to 1 8th
    LFO3MS,      // -200,200 ms
  LFO3Sharpness,

  LFO4Waveform,  // KEEP IN SYNC WITH LFOParamIndexOffsets
  LFO4WaveshapeA,
  LFO4WaveshapeB,
  LFO4Restart,  // if restart, then LFO is per voice. if no restart, then it's per synth.
  LFO4PhaseOffset,
  LFO4FrequencyParam,
  LFO4TimeBasis, // enum TimeBasis
    LFO4BeatNumerator,
    LFO4BeatDenominator,
    LFO4EighthsFine,    // -1 to 1 8th
    LFO4MS,      // -200,200 ms
  LFO4Sharpness,

  Filter1Enabled,
  Filter1Circuit,
  Filter1Slope,
  Filter1Response,
  Filter1Q,
  Filter1Freq,
  Filter1FreqKT,

  Filter2Enabled,
  Filter2Circuit,
  Filter2Slope,
  Filter2Response,
  Filter2Q,
  Filter2Freq,
  Filter2FreqKT,

  Mod1Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod1Source,
  Mod1Destination1,
  Mod1Destination2,
  Mod1Destination3,
  Mod1Destination4,
  Mod1Curve,
  Mod1Scale1,
  Mod1Scale2,
  Mod1Scale3,
  Mod1Scale4,
  Mod1AuxEnabled,
  Mod1AuxSource,
  Mod1AuxAttenuation,
  Mod1AuxCurve,
  Mod1SrcRangeMin,
  Mod1SrcRangeMax,
  Mod1AuxRangeMin,
  Mod1AuxRangeMax,

  Mod2Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod2Source,
  Mod2Destination1,
  Mod2Destination2,
  Mod2Destination3,
  Mod2Destination4,
  Mod2Curve,
  Mod2Scale1,
  Mod2Scale2,
  Mod2Scale3,
  Mod2Scale4,
  Mod2AuxEnabled,
  Mod2AuxSource,
  Mod2AuxAttenuation,
  Mod2AuxCurve,
  Mod2SrcRangeMin,
  Mod2SrcRangeMax,
  Mod2AuxRangeMin,
  Mod2AuxRangeMax,

  Mod3Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod3Source,
  Mod3Destination1,
  Mod3Destination2,
  Mod3Destination3,
  Mod3Destination4,
  Mod3Curve,
  Mod3Scale1,
  Mod3Scale2,
  Mod3Scale3,
  Mod3Scale4,
  Mod3AuxEnabled,
  Mod3AuxSource,
  Mod3AuxAttenuation,
  Mod3AuxCurve,
  Mod3SrcRangeMin,
  Mod3SrcRangeMax,
  Mod3AuxRangeMin,
  Mod3AuxRangeMax,

  Mod4Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod4Source,
  Mod4Destination1,
  Mod4Destination2,
  Mod4Destination3,
  Mod4Destination4,
  Mod4Curve,
  Mod4Scale1,
  Mod4Scale2,
  Mod4Scale3,
  Mod4Scale4,
  Mod4AuxEnabled,
  Mod4AuxSource,
  Mod4AuxAttenuation,
  Mod4AuxCurve,
  Mod4SrcRangeMin,
  Mod4SrcRangeMax,
  Mod4AuxRangeMin,
  Mod4AuxRangeMax,

  Mod5Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod5Source,
  Mod5Destination1,
  Mod5Destination2,
  Mod5Destination3,
  Mod5Destination4,
  Mod5Curve,
  Mod5Scale1,
  Mod5Scale2,
  Mod5Scale3,
  Mod5Scale4,
  Mod5AuxEnabled,
  Mod5AuxSource,
  Mod5AuxAttenuation,
  Mod5AuxCurve,
  Mod5SrcRangeMin,
  Mod5SrcRangeMax,
  Mod5AuxRangeMin,
  Mod5AuxRangeMax,

  Mod6Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod6Source,
  Mod6Destination1,
  Mod6Destination2,
  Mod6Destination3,
  Mod6Destination4,
  Mod6Curve,
  Mod6Scale1,
  Mod6Scale2,
  Mod6Scale3,
  Mod6Scale4,
  Mod6AuxEnabled,
  Mod6AuxSource,
  Mod6AuxAttenuation,
  Mod6AuxCurve,
  Mod6SrcRangeMin,
  Mod6SrcRangeMax,
  Mod6AuxRangeMin,
  Mod6AuxRangeMax,

  Mod7Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod7Source,
  Mod7Destination1,
  Mod7Destination2,
  Mod7Destination3,
  Mod7Destination4,
  Mod7Curve,
  Mod7Scale1,
  Mod7Scale2,
  Mod7Scale3,
  Mod7Scale4,
  Mod7AuxEnabled,
  Mod7AuxSource,
  Mod7AuxAttenuation,
  Mod7AuxCurve,
  Mod7SrcRangeMin,
  Mod7SrcRangeMax,
  Mod7AuxRangeMin,
  Mod7AuxRangeMax,

  Mod8Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod8Source,
  Mod8Destination1,
  Mod8Destination2,
  Mod8Destination3,
  Mod8Destination4,
  Mod8Curve,
  Mod8Scale1,
  Mod8Scale2,
  Mod8Scale3,
  Mod8Scale4,
  Mod8AuxEnabled,
  Mod8AuxSource,
  Mod8AuxAttenuation,
  Mod8AuxCurve,
  Mod8SrcRangeMin,
  Mod8SrcRangeMax,
  Mod8AuxRangeMin,
  Mod8AuxRangeMax,

  Mod9Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod9Source,
  Mod9Destination1,
  Mod9Destination2,
  Mod9Destination3,
  Mod9Destination4,
  Mod9Curve,
  Mod9Scale1,
  Mod9Scale2,
  Mod9Scale3,
  Mod9Scale4,
  Mod9AuxEnabled,
  Mod9AuxSource,
  Mod9AuxAttenuation,
  Mod9AuxCurve,
  Mod9SrcRangeMin,
  Mod9SrcRangeMax,
  Mod9AuxRangeMin,
  Mod9AuxRangeMax,

  Mod10Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod10Source,
  Mod10Destination1,
  Mod10Destination2,
  Mod10Destination3,
  Mod10Destination4,
  Mod10Curve,
  Mod10Scale1,
  Mod10Scale2,
  Mod10Scale3,
  Mod10Scale4,
  Mod10AuxEnabled,
  Mod10AuxSource,
  Mod10AuxAttenuation,
  Mod10AuxCurve,
  Mod10SrcRangeMin,
  Mod10SrcRangeMax,
  Mod10AuxRangeMin,
  Mod10AuxRangeMax,

  Mod11Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod11Source,
  Mod11Destination1,
  Mod11Destination2,
  Mod11Destination3,
  Mod11Destination4,
  Mod11Curve,
  Mod11Scale1,
  Mod11Scale2,
  Mod11Scale3,
  Mod11Scale4,
  Mod11AuxEnabled,
  Mod11AuxSource,
  Mod11AuxAttenuation,
  Mod11AuxCurve,
  Mod11SrcRangeMin,
  Mod11SrcRangeMax,
  Mod11AuxRangeMin,
  Mod11AuxRangeMax,

  Mod12Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod12Source,
  Mod12Destination1,
  Mod12Destination2,
  Mod12Destination3,
  Mod12Destination4,
  Mod12Curve,
  Mod12Scale1,
  Mod12Scale2,
  Mod12Scale3,
  Mod12Scale4,
  Mod12AuxEnabled,
  Mod12AuxSource,
  Mod12AuxAttenuation,
  Mod12AuxCurve,
  Mod12SrcRangeMin,
  Mod12SrcRangeMax,
  Mod12AuxRangeMin,
  Mod12AuxRangeMax,

  Mod13Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod13Source,
  Mod13Destination1,
  Mod13Destination2,
  Mod13Destination3,
  Mod13Destination4,
  Mod13Curve,
  Mod13Scale1,
  Mod13Scale2,
  Mod13Scale3,
  Mod13Scale4,
  Mod13AuxEnabled,
  Mod13AuxSource,
  Mod13AuxAttenuation,
  Mod13AuxCurve,
  Mod13SrcRangeMin,
  Mod13SrcRangeMax,
  Mod13AuxRangeMin,
  Mod13AuxRangeMax,

  Mod14Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod14Source,
  Mod14Destination1,
  Mod14Destination2,
  Mod14Destination3,
  Mod14Destination4,
  Mod14Curve,
  Mod14Scale1,
  Mod14Scale2,
  Mod14Scale3,
  Mod14Scale4,
  Mod14AuxEnabled,
  Mod14AuxSource,
  Mod14AuxAttenuation,
  Mod14AuxCurve,
  Mod14SrcRangeMin,
  Mod14SrcRangeMax,
  Mod14AuxRangeMin,
  Mod14AuxRangeMax,

  Mod15Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod15Source,
  Mod15Destination1,
  Mod15Destination2,
  Mod15Destination3,
  Mod15Destination4,
  Mod15Curve,
  Mod15Scale1,
  Mod15Scale2,
  Mod15Scale3,
  Mod15Scale4,
  Mod15AuxEnabled,
  Mod15AuxSource,
  Mod15AuxAttenuation,
  Mod15AuxCurve,
  Mod15SrcRangeMin,
  Mod15SrcRangeMax,
  Mod15AuxRangeMin,
  Mod15AuxRangeMax,

  Mod16Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod16Source,
  Mod16Destination1,
  Mod16Destination2,
  Mod16Destination3,
  Mod16Destination4,
  Mod16Curve,
  Mod16Scale1,
  Mod16Scale2,
  Mod16Scale3,
  Mod16Scale4,
  Mod16AuxEnabled,
  Mod16AuxSource,
  Mod16AuxAttenuation,
  Mod16AuxCurve,
  Mod16SrcRangeMin,
  Mod16SrcRangeMax,
  Mod16AuxRangeMin,
  Mod16AuxRangeMax,

  Mod17Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod17Source,
  Mod17Destination1,
  Mod17Destination2,
  Mod17Destination3,
  Mod17Destination4,
  Mod17Curve,
  Mod17Scale1,
  Mod17Scale2,
  Mod17Scale3,
  Mod17Scale4,
  Mod17AuxEnabled,
  Mod17AuxSource,
  Mod17AuxAttenuation,
  Mod17AuxCurve,
  Mod17SrcRangeMin,
  Mod17SrcRangeMax,
  Mod17AuxRangeMin,
  Mod17AuxRangeMax,

  Mod18Enabled,  // KEEP IN SYNC WITH ModParamIndexOffsets
  Mod18Source,
  Mod18Destination1,
  Mod18Destination2,
  Mod18Destination3,
  Mod18Destination4,
  Mod18Curve,
  Mod18Scale1,
  Mod18Scale2,
  Mod18Scale3,
  Mod18Scale4,
  Mod18AuxEnabled,
  Mod18AuxSource,
  Mod18AuxAttenuation,
  Mod18AuxCurve,
  Mod18SrcRangeMin,
  Mod18SrcRangeMax,
  Mod18AuxRangeMin,
  Mod18AuxRangeMax,

  Sampler1Enabled,  // KEEP IN SYNC WITH SamplerParamIndexOffsets
  Sampler1Volume,
  Sampler1Pan,
  Sampler1CompensationGain,
  Sampler1KeyrangeMin,
  Sampler1KeyrangeMax,
  Sampler1BaseNote,
  Sampler1LegatoTrig,
  Sampler1Reverse,
  Sampler1Source,  // gmdls or own sample
  Sampler1GmDlsIndex,
  Sampler1SampleStart,
  Sampler1LoopMode,
  Sampler1LoopSource,
  Sampler1LoopStart,
  Sampler1LoopLength,
  Sampler1TuneSemis,
  Sampler1TuneFine,
  Sampler1FreqParam,
  Sampler1FreqKT,
  Sampler1ReleaseExitsLoop,
  Sampler1Delay,

  Sampler1AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Sampler1AmpEnvAttackTime,
  Sampler1AmpEnvAttackCurve,
  Sampler1AmpEnvHoldTime,
  Sampler1AmpEnvDecayTime,
  Sampler1AmpEnvDecayCurve,
  Sampler1AmpEnvSustainLevel,
  Sampler1AmpEnvReleaseTime,
  Sampler1AmpEnvReleaseCurve,
  Sampler1AmpEnvLegatoRestart,
  Sampler1AmpEnvMode,

  Sampler2Enabled,  // KEEP IN SYNC WITH SamplerParamIndexOffsets
  Sampler2Volume,
  Sampler2Pan,
  Sampler2CompensationGain,
  Sampler2KeyrangeMin,
  Sampler2KeyrangeMax,
  Sampler2BaseNote,
  Sampler2LegatoTrig,
  Sampler2Reverse,
  Sampler2Source,  // gmdls or own sample
  Sampler2GmDlsIndex,
  Sampler2SampleStart,
  Sampler2LoopMode,
  Sampler2LoopSource,
  Sampler2LoopStart,
  Sampler2LoopLength,
  Sampler2TuneSemis,
  Sampler2TuneFine,
  Sampler2FreqParam,
  Sampler2FreqKT,
  Sampler2ReleaseExitsLoop,
  Sampler2Delay,

  Sampler2AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Sampler2AmpEnvAttackTime,
  Sampler2AmpEnvAttackCurve,
  Sampler2AmpEnvHoldTime,
  Sampler2AmpEnvDecayTime,
  Sampler2AmpEnvDecayCurve,
  Sampler2AmpEnvSustainLevel,
  Sampler2AmpEnvReleaseTime,
  Sampler2AmpEnvReleaseCurve,
  Sampler2AmpEnvLegatoRestart,
  Sampler2AmpEnvMode,

  Sampler3Enabled,  // KEEP IN SYNC WITH SamplerParamIndexOffsets
  Sampler3Volume,
  Sampler3Pan,
  Sampler3CompensationGain,
  Sampler3KeyrangeMin,
  Sampler3KeyrangeMax,
  Sampler3BaseNote,
  Sampler3LegatoTrig,
  Sampler3Reverse,
  Sampler3Source,  // gmdls or own sample
  Sampler3GmDlsIndex,
  Sampler3SampleStart,
  Sampler3LoopMode,
  Sampler3LoopSource,
  Sampler3LoopStart,
  Sampler3LoopLength,
  Sampler3TuneSemis,
  Sampler3TuneFine,
  Sampler3FreqParam,
  Sampler3FreqKT,
  Sampler3ReleaseExitsLoop,
  Sampler3Delay,

  Sampler3AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Sampler3AmpEnvAttackTime,
  Sampler3AmpEnvAttackCurve,
  Sampler3AmpEnvHoldTime,
  Sampler3AmpEnvDecayTime,
  Sampler3AmpEnvDecayCurve,
  Sampler3AmpEnvSustainLevel,
  Sampler3AmpEnvReleaseTime,
  Sampler3AmpEnvReleaseCurve,
  Sampler3AmpEnvLegatoRestart,
  Sampler3AmpEnvMode,

  Sampler4Enabled,  // KEEP IN SYNC WITH SamplerParamIndexOffsets
  Sampler4Volume,
  Sampler4Pan,
  Sampler4CompensationGain,
  Sampler4KeyrangeMin,
  Sampler4KeyrangeMax,
  Sampler4BaseNote,
  Sampler4LegatoTrig,
  Sampler4Reverse,
  Sampler4Source,  // gmdls or own sample
  Sampler4GmDlsIndex,
  Sampler4SampleStart,
  Sampler4LoopMode,
  Sampler4LoopSource,
  Sampler4LoopStart,
  Sampler4LoopLength,
  Sampler4TuneSemis,
  Sampler4TuneFine,
  Sampler4FreqParam,
  Sampler4FreqKT,
  Sampler4ReleaseExitsLoop,
  Sampler4Delay,

  Sampler4AmpEnvDelayTime,  // KEEP IN SYNC WITH EnvParamIndexOffsets
  Sampler4AmpEnvAttackTime,
  Sampler4AmpEnvAttackCurve,
  Sampler4AmpEnvHoldTime,
  Sampler4AmpEnvDecayTime,
  Sampler4AmpEnvDecayCurve,
  Sampler4AmpEnvSustainLevel,
  Sampler4AmpEnvReleaseTime,
  Sampler4AmpEnvReleaseCurve,
  Sampler4AmpEnvLegatoRestart,
  Sampler4AmpEnvMode,

  NumParams,
  Invalid,
};

// clang-format on
}  // namespace WaveSabreCore::M7
